### PR TITLE
Google Calendar integration

### PR DESCRIPTION
**Pull request by ffflorian**
This plugin adds integration for [Google Calendar](https://calendar.google.com).
Notification alerts are displayed in a simple modal, see #17.

### CODE REVIEW

**Comment by Decipher** [comment]
:+1:

Tested and works well.

**Comment by Decipher** [comment]
A bit of feedback; I found the notification, while extremely helpful that it popped up in Franz, was a little too small for the information it was presenting (primarily a Hangout URL). On top of that, and probably more of a Franz issue than this PR, I was unable to copy the URL from the popup, so I ended up having to open Google Cal in a browser anyway.

**Comment by ffflorian** [comment]
Thanks @Decipher for the feedback. The notification is really not beautiful yet and I'll improve it in the next days.

**Comment by Lazza** [comment]
I'm curious: given that Franz is "a free messaging app for [...]", what would be the point of including non-messaging web apps into it, like Google Calendar or Buffer that was suggested in another  PR?

This is not criticism, I'm just trying to understand the idea behind it and I am trying to think if I also know some other web app that would be meaningful inside Franz.

**Comment by ffflorian** [comment]
> what would be the point of including non-messaging web apps into it?

@Lazza: You're right, from a messaging point of view, it doesn't make sense. But I see Franz as a general web app tool so I create plugins for web apps I find useful.

It's the author's choice to accept the PR or not - we will see :)

Thanks for the input though!

**Comment by Lazza** [comment]
Yeah, we will see... :blush: The weird thing is that no plugin PR has been accepted til now.

**Comment by ffflorian** [comment]
> The weird thing is that no plugin PR has been accepted til now.

I think he is/they are still fixing bugs like #7 first before accepting any PRs.

**Comment by adlk** [comment]
> I think he is/they are still fixing bugs like #7 first before accepting any PRs.
Yep, that was the reason, especially since some of the plugins were created with a fixed serviceURL. Oh and we've just softlaunched 4.0.3 with #7 fixed. 

Ad is Calendar a fit for Franz? One of the reasons why we have added support for custom integrations is to open up Franz and move towards a messaging & productivity centric application framework. 

For now, there is a very simple set of rules on how to get accepted:
- no duplicates
- no malicious code

**Comment by ffflorian** [comment]
@Decipher 
> I found the notification, while extremely helpful that it popped up in Franz, was a little too small for the information it was presenting (primarily a Hangout URL)

Could you please provide a screenshot for a notification with a Hangout URL?

**Comment by Decipher** [comment]
@ffflorian Sure, will do today.

**Comment by ffflorian** [comment]
@Decipher What about the screenshots? :) I never had a notification which was too large yet so I'd be interested to see a buggy notification.

**Comment by Decipher** [comment]
@ffflorian unfortunately the Google calendar plugin just hasn't worked for me since I made that last post, just results in a blank page, and I don't have enough free time to look into why.

**Comment by ffflorian** [comment]
@Decipher It's possible that Franz has a hiccup because of a version change. If you have time, please close Franz, delete the `googlecalendar` folder and delete all related configs in the Franz config file. Then copy the `googlecalendar` folder again and restart Franz. Thank you :)

**Pull request merged**
