### PR TITLE
Add Recipe for Android Messages

### PR DESCRIPTION
**Pull request by dweinber**
Including unread message badge count

### CODE REVIEW

**Comment by mikeseese** [comment]
While the implementation for unread message count does work currently, it uses what looks like generated CSS classes, which is unreliable as they change when they build the CSS files again. I feel like there has to be a more robust method for getting the unread count. With that said, I think this should get merged, but a better solution should be considered for message count for the future.

Thanks for making the recipe @dweinber!

**Comment by dweinber** [comment]
Agree, I'm not happy with the unread count but couldn't find something better so far. Definitely open to suggestions and will also look again if I can find a better way.

**Comment by mikeseese** [comment]
Please see my pull request @dweinber https://github.com/dweinber/franz-recipe-android-messages/pull/3 :)

**Comment by taylorjdawson** [comment]
When will this PR get accepted?

**Comment by yassinecc** [comment]
ping @adlk

**Pull request merged**
