### PR TITLE
Fixes for Office 365 Outlook

### PR DESCRIPTION
**Pull request by lucymhdavies**
Doesn't do unread email numbers. I've not figured that out yet.

But it's a start.

This is different to the built-in outlook.com. Microsoft keeps those separate for some reason.

### CODE REVIEW

**Comment by logTom** [comment]
Unread email numbers:

$('span[autoid=_n_V]').eq(0).text();

This gives me the unread count for my first favorite folder. Does it also work for you?

This would be a hacky solution until we find some better way to get it.

**Comment by lucymhdavies** [comment]
A hacky solution is better than no solution :)

**Comment by logTom** [comment]
https://github.com/meetfranz/plugins/commit/ed5a157d5159ed272f6d236e52c68af4d6992198
I guess we can close this now.

**Comment by lucymhdavies** [comment]
Yeah.

https://github.com/meetfranz/plugins/commit/ed5a157d5159ed272f6d236e52c68af4d6992198#diff-3127865a047c39095085be22dd60cf19

Looks better than my version :)

**Comment by lucymhdavies** [comment]
However, there's a typo in that one.

I'll update this PR to fix it.

**Comment by chris-gray** [comment]
Ah thank you! That had been annoying me for a while and hadn't got round to fixing it! :-)

**Comment by lucymhdavies** [comment]
Not half as much as having to use Office365 in the first place is annoying me ;)

**Comment by antda** [comment]
The title of my inbox is unfortunately 'Inkorg' (Swedish) so the unread-mail counter does not work for me

**Comment by daniel88ferreira** [comment]
Hello,
How is this office365 plugin?
Cannot pass login page after putting my company's email address. It says redirecting and then a blank page.
Thanks in advance.

**Comment by lucymhdavies** [comment]
Works fine for me. It's https://outlook.office365.com

**Comment by daniel88ferreira** [comment]
maybe I'm doing something wrong.
I have to be redirected here: https://outlook.office.com/owa/?realm=nokia.com
But after login I just get a blank page.

**Comment by lucymhdavies** [comment]
Yes, that sounds correct.
Presumably you do not get the same issue in your browser?

**Comment by daniel88ferreira** [comment]
no, I don't, tried with Firefox and Chrome ... Later I can try again from outside the company's network, just to test if  I run into the same issue.

**Comment by daniel88ferreira** [comment]
Hello, I think that's some problem with the proxy.
I've tried to connect from home (same PC, no proxy) and I can use the plugin successfully.
Can you help me find the logs for Franz and for your plugin? If so, I can send some logs.
thx

**Pull request merged**
